// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	ViewModel.tt
// Version:		2.0
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls = WPAppStudio.Controls;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;
using IServices = WPAppStudio.Services.Interfaces;
using IViewModels = WPAppStudio.ViewModel.Interfaces;
using Localization = WPAppStudio.Localization;
using Repositories = WPAppStudio.Repositories;
using Services = WPAppStudio.Services;
using ViewModelsBase = WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of intheaters_Detail ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class intheaters_DetailViewModel : ViewModelsBase.VMBase, IViewModels.Iintheaters_DetailViewModel, ViewModelsBase.INavigable
    {       

		private readonly Repositories.intheaters_openingMoviesDataSource _intheaters_openingMoviesDataSource;
		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly IServices.ISpeechService _speechService;
		private readonly IServices.IShareService _shareService;
		private readonly IServices.ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="intheaters_DetailViewModel" /> class.
        /// </summary>
        /// <param name="intheaters_openingMoviesDataSource">The Intheaters_opening Movies Data Source.</param>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public intheaters_DetailViewModel(Repositories.intheaters_openingMoviesDataSource intheaters_openingMoviesDataSource, IServices.IDialogService dialogService, IServices.INavigationService navigationService, IServices.ISpeechService speechService, IServices.IShareService shareService, IServices.ILiveTileService liveTileService)
        {
			_intheaters_openingMoviesDataSource = intheaters_openingMoviesDataSource;
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		
	
		private EntitiesBase.RssSearchResult _currentRssSearchResult;

        /// <summary>
        /// CurrentRssSearchResult property.
        /// </summary>		
        public EntitiesBase.RssSearchResult CurrentRssSearchResult
        {
            get
            {
				return _currentRssSearchResult;
            }
            set
            {
                SetProperty(ref _currentRssSearchResult, value);
            }
        }
	
		private bool _hasNextpanoramaintheaters_Detail0;

        /// <summary>
        /// HasNextpanoramaintheaters_Detail0 property.
        /// </summary>		
        public bool HasNextpanoramaintheaters_Detail0
        {
            get
            {
				return _hasNextpanoramaintheaters_Detail0;
            }
            set
            {
                SetProperty(ref _hasNextpanoramaintheaters_Detail0, value);
            }
        }
	
		private bool _hasPreviouspanoramaintheaters_Detail0;

        /// <summary>
        /// HasPreviouspanoramaintheaters_Detail0 property.
        /// </summary>		
        public bool HasPreviouspanoramaintheaters_Detail0
        {
            get
            {
				return _hasPreviouspanoramaintheaters_Detail0;
            }
            set
            {
                SetProperty(ref _hasPreviouspanoramaintheaters_Detail0, value);
            }
        }
	    /// <summary>
        /// IsInternetAvailable property.
        /// </summary>		
        public override Visibility IsInternetAvailable
        {
	      get
          {
				return Visibility.Collapsed; 
           }
		}

        /// <summary>
        /// Delegate method for the TextToSpeechintheaters_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechintheaters_DetailStaticControlCommandDelegate() 
        {
				_speechService.TextToSpeech(CurrentRssSearchResult.Title + " " + CurrentRssSearchResult.Content);
        }
		

        private ICommand _textToSpeechintheaters_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechintheaters_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechintheaters_DetailStaticControlCommand
        {
            get { return _textToSpeechintheaters_DetailStaticControlCommand = _textToSpeechintheaters_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(TextToSpeechintheaters_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the Shareintheaters_DetailStaticControlCommand command.
        /// </summary>
        public  void Shareintheaters_DetailStaticControlCommandDelegate() 
        {
				_shareService.Share(CurrentRssSearchResult.Title, CurrentRssSearchResult.Content, CurrentRssSearchResult.FeedUrl, CurrentRssSearchResult.ImageUrl);
        }
		

        private ICommand _shareintheaters_DetailStaticControlCommand;

        /// <summary>
        /// Gets the Shareintheaters_DetailStaticControlCommand command.
        /// </summary>
        public ICommand Shareintheaters_DetailStaticControlCommand
        {
            get { return _shareintheaters_DetailStaticControlCommand = _shareintheaters_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(Shareintheaters_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartintheaters_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartintheaters_DetailStaticControlCommandDelegate() 
        {
				_liveTileService.PinToStart(typeof(IViewModels.Iintheaters_DetailViewModel), CreateTileInfointheaters_DetailStaticControl());
        }
		

        private ICommand _pinToStartintheaters_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartintheaters_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartintheaters_DetailStaticControlCommand
        {
            get { return _pinToStartintheaters_DetailStaticControlCommand = _pinToStartintheaters_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(PinToStartintheaters_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the GoToSourceintheaters_DetailStaticControlCommand command.
        /// </summary>
        public  void GoToSourceintheaters_DetailStaticControlCommandDelegate() 
        {
				_navigationService.NavigateTo(string.IsNullOrEmpty(CurrentRssSearchResult.FeedUrl) ? null : new Uri(CurrentRssSearchResult.FeedUrl));
        }
		

        private ICommand _goToSourceintheaters_DetailStaticControlCommand;

        /// <summary>
        /// Gets the GoToSourceintheaters_DetailStaticControlCommand command.
        /// </summary>
        public ICommand GoToSourceintheaters_DetailStaticControlCommand
        {
            get { return _goToSourceintheaters_DetailStaticControlCommand = _goToSourceintheaters_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(GoToSourceintheaters_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the Nextpanoramaintheaters_Detail0 command.
        /// </summary>
        public async void Nextpanoramaintheaters_Detail0Delegate() 
        {
				LoadingCurrentRssSearchResult = true;
			var next = await  _intheaters_openingMoviesDataSource.Next(CurrentRssSearchResult);

			if(next != null)
				CurrentRssSearchResult = next;

			RefreshHasPrevNext();
        }
		
		
        private bool _loadingCurrentRssSearchResult;
		
        public bool LoadingCurrentRssSearchResult
        {
            get { return _loadingCurrentRssSearchResult; }
            set { SetProperty(ref _loadingCurrentRssSearchResult, value); }
        }

        private ICommand _nextpanoramaintheaters_Detail0;

        /// <summary>
        /// Gets the Nextpanoramaintheaters_Detail0 command.
        /// </summary>
        public ICommand Nextpanoramaintheaters_Detail0
        {
            get { return _nextpanoramaintheaters_Detail0 = _nextpanoramaintheaters_Detail0 ?? new ViewModelsBase.DelegateCommand(Nextpanoramaintheaters_Detail0Delegate); }
        }

        /// <summary>
        /// Delegate method for the Previouspanoramaintheaters_Detail0 command.
        /// </summary>
        public async void Previouspanoramaintheaters_Detail0Delegate() 
        {
				LoadingCurrentRssSearchResult = true;
			var prev = await  _intheaters_openingMoviesDataSource.Previous(CurrentRssSearchResult);

			if(prev != null)
				CurrentRssSearchResult = prev;

			RefreshHasPrevNext();
        }
		

        private ICommand _previouspanoramaintheaters_Detail0;

        /// <summary>
        /// Gets the Previouspanoramaintheaters_Detail0 command.
        /// </summary>
        public ICommand Previouspanoramaintheaters_Detail0
        {
            get { return _previouspanoramaintheaters_Detail0 = _previouspanoramaintheaters_Detail0 ?? new ViewModelsBase.DelegateCommand(Previouspanoramaintheaters_Detail0Delegate); }
        }

        private async void RefreshHasPrevNext()
        {
            HasPreviouspanoramaintheaters_Detail0 = await _intheaters_openingMoviesDataSource.HasPrevious(CurrentRssSearchResult);
			HasNextpanoramaintheaters_Detail0 = await _intheaters_openingMoviesDataSource.HasNext(CurrentRssSearchResult);
			LoadingCurrentRssSearchResult = false;
		}
		public object NavigationContext
        {
            set
            {              
                if (!(value is EntitiesBase.RssSearchResult)) { return; }
                
                CurrentRssSearchResult = value as EntitiesBase.RssSearchResult;
                RefreshHasPrevNext();
            }
        }
        /// <summary>
        /// Initializes a <see cref="Services.TileInfo" /> object for the intheaters_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="Services.TileInfo" /> object.</returns>
        public Services.TileInfo CreateTileInfointheaters_DetailStaticControl()
        {
            var tileInfo = new Services.TileInfo
            {
                CurrentId = CurrentRssSearchResult.Title,
                Title = CurrentRssSearchResult.Title,
                BackTitle = CurrentRssSearchResult.Title,
                BackContent = CurrentRssSearchResult.Content,
                Count = 0,
                BackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                BackBackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                LogoPath = "Logo-ee1683e8-d47b-47fb-83b9-cfccc204fafa.png"
            };
            return tileInfo;
        }
    }
}
