// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	ViewModel.tt
// Version:		2.0
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls = WPAppStudio.Controls;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;
using IServices = WPAppStudio.Services.Interfaces;
using IViewModels = WPAppStudio.ViewModel.Interfaces;
using Localization = WPAppStudio.Localization;
using Repositories = WPAppStudio.Repositories;
using Services = WPAppStudio.Services;
using ViewModelsBase = WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of moviebuzz_Detail ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class moviebuzz_DetailViewModel : ViewModelsBase.VMBase, IViewModels.Imoviebuzz_DetailViewModel, ViewModelsBase.INavigable
    {       

		private readonly Repositories.moviebuzz_reviewsDataSource _moviebuzz_reviewsDataSource;
		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly IServices.ISpeechService _speechService;
		private readonly IServices.IShareService _shareService;
		private readonly IServices.ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="moviebuzz_DetailViewModel" /> class.
        /// </summary>
        /// <param name="moviebuzz_reviewsDataSource">The Moviebuzz_reviews Data Source.</param>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public moviebuzz_DetailViewModel(Repositories.moviebuzz_reviewsDataSource moviebuzz_reviewsDataSource, IServices.IDialogService dialogService, IServices.INavigationService navigationService, IServices.ISpeechService speechService, IServices.IShareService shareService, IServices.ILiveTileService liveTileService)
        {
			_moviebuzz_reviewsDataSource = moviebuzz_reviewsDataSource;
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		
	
		private EntitiesBase.RssSearchResult _currentRssSearchResult;

        /// <summary>
        /// CurrentRssSearchResult property.
        /// </summary>		
        public EntitiesBase.RssSearchResult CurrentRssSearchResult
        {
            get
            {
				return _currentRssSearchResult;
            }
            set
            {
                SetProperty(ref _currentRssSearchResult, value);
            }
        }
	
		private bool _hasNextpanoramamoviebuzz_Detail0;

        /// <summary>
        /// HasNextpanoramamoviebuzz_Detail0 property.
        /// </summary>		
        public bool HasNextpanoramamoviebuzz_Detail0
        {
            get
            {
				return _hasNextpanoramamoviebuzz_Detail0;
            }
            set
            {
                SetProperty(ref _hasNextpanoramamoviebuzz_Detail0, value);
            }
        }
	
		private bool _hasPreviouspanoramamoviebuzz_Detail0;

        /// <summary>
        /// HasPreviouspanoramamoviebuzz_Detail0 property.
        /// </summary>		
        public bool HasPreviouspanoramamoviebuzz_Detail0
        {
            get
            {
				return _hasPreviouspanoramamoviebuzz_Detail0;
            }
            set
            {
                SetProperty(ref _hasPreviouspanoramamoviebuzz_Detail0, value);
            }
        }
	    /// <summary>
        /// IsInternetAvailable property.
        /// </summary>		
        public override Visibility IsInternetAvailable
        {
	      get
          {
				return Visibility.Collapsed; 
           }
		}

        /// <summary>
        /// Delegate method for the TextToSpeechmoviebuzz_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechmoviebuzz_DetailStaticControlCommandDelegate() 
        {
				_speechService.TextToSpeech(CurrentRssSearchResult.Title + " " + CurrentRssSearchResult.Content);
        }
		

        private ICommand _textToSpeechmoviebuzz_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechmoviebuzz_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechmoviebuzz_DetailStaticControlCommand
        {
            get { return _textToSpeechmoviebuzz_DetailStaticControlCommand = _textToSpeechmoviebuzz_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(TextToSpeechmoviebuzz_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the Sharemoviebuzz_DetailStaticControlCommand command.
        /// </summary>
        public  void Sharemoviebuzz_DetailStaticControlCommandDelegate() 
        {
				_shareService.Share(CurrentRssSearchResult.Title, CurrentRssSearchResult.Content, CurrentRssSearchResult.FeedUrl, CurrentRssSearchResult.ImageUrl);
        }
		

        private ICommand _sharemoviebuzz_DetailStaticControlCommand;

        /// <summary>
        /// Gets the Sharemoviebuzz_DetailStaticControlCommand command.
        /// </summary>
        public ICommand Sharemoviebuzz_DetailStaticControlCommand
        {
            get { return _sharemoviebuzz_DetailStaticControlCommand = _sharemoviebuzz_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(Sharemoviebuzz_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartmoviebuzz_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartmoviebuzz_DetailStaticControlCommandDelegate() 
        {
				_liveTileService.PinToStart(typeof(IViewModels.Imoviebuzz_DetailViewModel), CreateTileInfomoviebuzz_DetailStaticControl());
        }
		

        private ICommand _pinToStartmoviebuzz_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartmoviebuzz_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartmoviebuzz_DetailStaticControlCommand
        {
            get { return _pinToStartmoviebuzz_DetailStaticControlCommand = _pinToStartmoviebuzz_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(PinToStartmoviebuzz_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the GoToSourcemoviebuzz_DetailStaticControlCommand command.
        /// </summary>
        public  void GoToSourcemoviebuzz_DetailStaticControlCommandDelegate() 
        {
				_navigationService.NavigateTo(string.IsNullOrEmpty(CurrentRssSearchResult.FeedUrl) ? null : new Uri(CurrentRssSearchResult.FeedUrl));
        }
		

        private ICommand _goToSourcemoviebuzz_DetailStaticControlCommand;

        /// <summary>
        /// Gets the GoToSourcemoviebuzz_DetailStaticControlCommand command.
        /// </summary>
        public ICommand GoToSourcemoviebuzz_DetailStaticControlCommand
        {
            get { return _goToSourcemoviebuzz_DetailStaticControlCommand = _goToSourcemoviebuzz_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(GoToSourcemoviebuzz_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the Nextpanoramamoviebuzz_Detail0 command.
        /// </summary>
        public async void Nextpanoramamoviebuzz_Detail0Delegate() 
        {
				LoadingCurrentRssSearchResult = true;
			var next = await  _moviebuzz_reviewsDataSource.Next(CurrentRssSearchResult);

			if(next != null)
				CurrentRssSearchResult = next;

			RefreshHasPrevNext();
        }
		
		
        private bool _loadingCurrentRssSearchResult;
		
        public bool LoadingCurrentRssSearchResult
        {
            get { return _loadingCurrentRssSearchResult; }
            set { SetProperty(ref _loadingCurrentRssSearchResult, value); }
        }

        private ICommand _nextpanoramamoviebuzz_Detail0;

        /// <summary>
        /// Gets the Nextpanoramamoviebuzz_Detail0 command.
        /// </summary>
        public ICommand Nextpanoramamoviebuzz_Detail0
        {
            get { return _nextpanoramamoviebuzz_Detail0 = _nextpanoramamoviebuzz_Detail0 ?? new ViewModelsBase.DelegateCommand(Nextpanoramamoviebuzz_Detail0Delegate); }
        }

        /// <summary>
        /// Delegate method for the Previouspanoramamoviebuzz_Detail0 command.
        /// </summary>
        public async void Previouspanoramamoviebuzz_Detail0Delegate() 
        {
				LoadingCurrentRssSearchResult = true;
			var prev = await  _moviebuzz_reviewsDataSource.Previous(CurrentRssSearchResult);

			if(prev != null)
				CurrentRssSearchResult = prev;

			RefreshHasPrevNext();
        }
		

        private ICommand _previouspanoramamoviebuzz_Detail0;

        /// <summary>
        /// Gets the Previouspanoramamoviebuzz_Detail0 command.
        /// </summary>
        public ICommand Previouspanoramamoviebuzz_Detail0
        {
            get { return _previouspanoramamoviebuzz_Detail0 = _previouspanoramamoviebuzz_Detail0 ?? new ViewModelsBase.DelegateCommand(Previouspanoramamoviebuzz_Detail0Delegate); }
        }

        private async void RefreshHasPrevNext()
        {
            HasPreviouspanoramamoviebuzz_Detail0 = await _moviebuzz_reviewsDataSource.HasPrevious(CurrentRssSearchResult);
			HasNextpanoramamoviebuzz_Detail0 = await _moviebuzz_reviewsDataSource.HasNext(CurrentRssSearchResult);
			LoadingCurrentRssSearchResult = false;
		}
		public object NavigationContext
        {
            set
            {              
                if (!(value is EntitiesBase.RssSearchResult)) { return; }
                
                CurrentRssSearchResult = value as EntitiesBase.RssSearchResult;
                RefreshHasPrevNext();
            }
        }
        /// <summary>
        /// Initializes a <see cref="Services.TileInfo" /> object for the moviebuzz_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="Services.TileInfo" /> object.</returns>
        public Services.TileInfo CreateTileInfomoviebuzz_DetailStaticControl()
        {
            var tileInfo = new Services.TileInfo
            {
                CurrentId = CurrentRssSearchResult.Title,
                Title = CurrentRssSearchResult.Title,
                BackTitle = CurrentRssSearchResult.Title,
                BackContent = CurrentRssSearchResult.Content,
                Count = 0,
                BackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                BackBackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                LogoPath = "Logo-ee1683e8-d47b-47fb-83b9-cfccc204fafa.png"
            };
            return tileInfo;
        }
    }
}
