// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	ViewModel.tt
// Version:		2.0
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls = WPAppStudio.Controls;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;
using IServices = WPAppStudio.Services.Interfaces;
using IViewModels = WPAppStudio.ViewModel.Interfaces;
using Localization = WPAppStudio.Localization;
using Repositories = WPAppStudio.Repositories;
using Services = WPAppStudio.Services;
using ViewModelsBase = WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of movieoftheweek_Detail ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class movieoftheweek_DetailViewModel : ViewModelsBase.VMBase, IViewModels.Imovieoftheweek_DetailViewModel, ViewModelsBase.INavigable
    {       

		private readonly Repositories.movieoftheweek_movieDataSource _movieoftheweek_movieDataSource;
		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly IServices.ISpeechService _speechService;
		private readonly IServices.IShareService _shareService;
		private readonly IServices.ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="movieoftheweek_DetailViewModel" /> class.
        /// </summary>
        /// <param name="movieoftheweek_movieDataSource">The Movieoftheweek_movie Data Source.</param>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public movieoftheweek_DetailViewModel(Repositories.movieoftheweek_movieDataSource movieoftheweek_movieDataSource, IServices.IDialogService dialogService, IServices.INavigationService navigationService, IServices.ISpeechService speechService, IServices.IShareService shareService, IServices.ILiveTileService liveTileService)
        {
			_movieoftheweek_movieDataSource = movieoftheweek_movieDataSource;
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		
	
		private EntitiesBase.RssSearchResult _currentRssSearchResult;

        /// <summary>
        /// CurrentRssSearchResult property.
        /// </summary>		
        public EntitiesBase.RssSearchResult CurrentRssSearchResult
        {
            get
            {
				return _currentRssSearchResult;
            }
            set
            {
                SetProperty(ref _currentRssSearchResult, value);
            }
        }
	
		private bool _hasNextpanoramamovieoftheweek_Detail0;

        /// <summary>
        /// HasNextpanoramamovieoftheweek_Detail0 property.
        /// </summary>		
        public bool HasNextpanoramamovieoftheweek_Detail0
        {
            get
            {
				return _hasNextpanoramamovieoftheweek_Detail0;
            }
            set
            {
                SetProperty(ref _hasNextpanoramamovieoftheweek_Detail0, value);
            }
        }
	
		private bool _hasPreviouspanoramamovieoftheweek_Detail0;

        /// <summary>
        /// HasPreviouspanoramamovieoftheweek_Detail0 property.
        /// </summary>		
        public bool HasPreviouspanoramamovieoftheweek_Detail0
        {
            get
            {
				return _hasPreviouspanoramamovieoftheweek_Detail0;
            }
            set
            {
                SetProperty(ref _hasPreviouspanoramamovieoftheweek_Detail0, value);
            }
        }
	    /// <summary>
        /// IsInternetAvailable property.
        /// </summary>		
        public override Visibility IsInternetAvailable
        {
	      get
          {
				return Visibility.Collapsed; 
           }
		}

        /// <summary>
        /// Delegate method for the TextToSpeechmovieoftheweek_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechmovieoftheweek_DetailStaticControlCommandDelegate() 
        {
				_speechService.TextToSpeech(CurrentRssSearchResult.Title + " " + CurrentRssSearchResult.Content);
        }
		

        private ICommand _textToSpeechmovieoftheweek_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechmovieoftheweek_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechmovieoftheweek_DetailStaticControlCommand
        {
            get { return _textToSpeechmovieoftheweek_DetailStaticControlCommand = _textToSpeechmovieoftheweek_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(TextToSpeechmovieoftheweek_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the Sharemovieoftheweek_DetailStaticControlCommand command.
        /// </summary>
        public  void Sharemovieoftheweek_DetailStaticControlCommandDelegate() 
        {
				_shareService.Share(CurrentRssSearchResult.Title, CurrentRssSearchResult.Content, CurrentRssSearchResult.FeedUrl, CurrentRssSearchResult.ImageUrl);
        }
		

        private ICommand _sharemovieoftheweek_DetailStaticControlCommand;

        /// <summary>
        /// Gets the Sharemovieoftheweek_DetailStaticControlCommand command.
        /// </summary>
        public ICommand Sharemovieoftheweek_DetailStaticControlCommand
        {
            get { return _sharemovieoftheweek_DetailStaticControlCommand = _sharemovieoftheweek_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(Sharemovieoftheweek_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartmovieoftheweek_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartmovieoftheweek_DetailStaticControlCommandDelegate() 
        {
				_liveTileService.PinToStart(typeof(IViewModels.Imovieoftheweek_DetailViewModel), CreateTileInfomovieoftheweek_DetailStaticControl());
        }
		

        private ICommand _pinToStartmovieoftheweek_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartmovieoftheweek_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartmovieoftheweek_DetailStaticControlCommand
        {
            get { return _pinToStartmovieoftheweek_DetailStaticControlCommand = _pinToStartmovieoftheweek_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(PinToStartmovieoftheweek_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the GoToSourcemovieoftheweek_DetailStaticControlCommand command.
        /// </summary>
        public  void GoToSourcemovieoftheweek_DetailStaticControlCommandDelegate() 
        {
				_navigationService.NavigateTo(string.IsNullOrEmpty(CurrentRssSearchResult.FeedUrl) ? null : new Uri(CurrentRssSearchResult.FeedUrl));
        }
		

        private ICommand _goToSourcemovieoftheweek_DetailStaticControlCommand;

        /// <summary>
        /// Gets the GoToSourcemovieoftheweek_DetailStaticControlCommand command.
        /// </summary>
        public ICommand GoToSourcemovieoftheweek_DetailStaticControlCommand
        {
            get { return _goToSourcemovieoftheweek_DetailStaticControlCommand = _goToSourcemovieoftheweek_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(GoToSourcemovieoftheweek_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the Nextpanoramamovieoftheweek_Detail0 command.
        /// </summary>
        public async void Nextpanoramamovieoftheweek_Detail0Delegate() 
        {
				LoadingCurrentRssSearchResult = true;
			var next = await  _movieoftheweek_movieDataSource.Next(CurrentRssSearchResult);

			if(next != null)
				CurrentRssSearchResult = next;

			RefreshHasPrevNext();
        }
		
		
        private bool _loadingCurrentRssSearchResult;
		
        public bool LoadingCurrentRssSearchResult
        {
            get { return _loadingCurrentRssSearchResult; }
            set { SetProperty(ref _loadingCurrentRssSearchResult, value); }
        }

        private ICommand _nextpanoramamovieoftheweek_Detail0;

        /// <summary>
        /// Gets the Nextpanoramamovieoftheweek_Detail0 command.
        /// </summary>
        public ICommand Nextpanoramamovieoftheweek_Detail0
        {
            get { return _nextpanoramamovieoftheweek_Detail0 = _nextpanoramamovieoftheweek_Detail0 ?? new ViewModelsBase.DelegateCommand(Nextpanoramamovieoftheweek_Detail0Delegate); }
        }

        /// <summary>
        /// Delegate method for the Previouspanoramamovieoftheweek_Detail0 command.
        /// </summary>
        public async void Previouspanoramamovieoftheweek_Detail0Delegate() 
        {
				LoadingCurrentRssSearchResult = true;
			var prev = await  _movieoftheweek_movieDataSource.Previous(CurrentRssSearchResult);

			if(prev != null)
				CurrentRssSearchResult = prev;

			RefreshHasPrevNext();
        }
		

        private ICommand _previouspanoramamovieoftheweek_Detail0;

        /// <summary>
        /// Gets the Previouspanoramamovieoftheweek_Detail0 command.
        /// </summary>
        public ICommand Previouspanoramamovieoftheweek_Detail0
        {
            get { return _previouspanoramamovieoftheweek_Detail0 = _previouspanoramamovieoftheweek_Detail0 ?? new ViewModelsBase.DelegateCommand(Previouspanoramamovieoftheweek_Detail0Delegate); }
        }

        private async void RefreshHasPrevNext()
        {
            HasPreviouspanoramamovieoftheweek_Detail0 = await _movieoftheweek_movieDataSource.HasPrevious(CurrentRssSearchResult);
			HasNextpanoramamovieoftheweek_Detail0 = await _movieoftheweek_movieDataSource.HasNext(CurrentRssSearchResult);
			LoadingCurrentRssSearchResult = false;
		}
		public object NavigationContext
        {
            set
            {              
                if (!(value is EntitiesBase.RssSearchResult)) { return; }
                
                CurrentRssSearchResult = value as EntitiesBase.RssSearchResult;
                RefreshHasPrevNext();
            }
        }
        /// <summary>
        /// Initializes a <see cref="Services.TileInfo" /> object for the movieoftheweek_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="Services.TileInfo" /> object.</returns>
        public Services.TileInfo CreateTileInfomovieoftheweek_DetailStaticControl()
        {
            var tileInfo = new Services.TileInfo
            {
                CurrentId = CurrentRssSearchResult.Title,
                Title = CurrentRssSearchResult.Title,
                BackTitle = CurrentRssSearchResult.Title,
                BackContent = CurrentRssSearchResult.Content,
                Count = 0,
                BackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                BackBackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                LogoPath = "Logo-ee1683e8-d47b-47fb-83b9-cfccc204fafa.png"
            };
            return tileInfo;
        }
    }
}
