// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	ViewModel.tt
// Version:		2.0
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls = WPAppStudio.Controls;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;
using IServices = WPAppStudio.Services.Interfaces;
using IViewModels = WPAppStudio.ViewModel.Interfaces;
using Localization = WPAppStudio.Localization;
using Repositories = WPAppStudio.Repositories;
using Services = WPAppStudio.Services;
using ViewModelsBase = WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of movieoftheweek_News ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class movieoftheweek_NewsViewModel : ViewModelsBase.VMBase, IViewModels.Imovieoftheweek_NewsViewModel
    {       

		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly Repositories.Imovieoftheweek_movieDataSource _movieoftheweek_movieDataSource;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="movieoftheweek_NewsViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="movieoftheweek_movieDataSource">The Movieoftheweek_movie Data Source.</param>
        public movieoftheweek_NewsViewModel(IServices.IDialogService dialogService, IServices.INavigationService navigationService, Repositories.Imovieoftheweek_movieDataSource movieoftheweek_movieDataSource)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_movieoftheweek_movieDataSource = movieoftheweek_movieDataSource;
        }
		
	
		private ObservableCollection<EntitiesBase.RssSearchResult> _movieoftheweek_NewsListControlCollection;

        /// <summary>
        /// Movieoftheweek_NewsListControlCollection property.
        /// </summary>		
        public ObservableCollection<EntitiesBase.RssSearchResult> Movieoftheweek_NewsListControlCollection
        {
            get
            {
				
                if(_movieoftheweek_NewsListControlCollection == null)
					Getmovieoftheweek_NewsListControlCollectionData();
				return _movieoftheweek_NewsListControlCollection;     
            }
            set
            {
                SetProperty(ref _movieoftheweek_NewsListControlCollection, value);
            }
        }
	
		private EntitiesBase.RssSearchResult _selectedmovieoftheweek_NewsListControlCollection;

        /// <summary>
        /// Selectedmovieoftheweek_NewsListControlCollection property.
        /// </summary>		
        public EntitiesBase.RssSearchResult Selectedmovieoftheweek_NewsListControlCollection
        {
            get
            {
				return _selectedmovieoftheweek_NewsListControlCollection;
            }
            set
            {
                _selectedmovieoftheweek_NewsListControlCollection = value;
                if (value != null)
                    _navigationService.NavigateTo<IViewModels.Imovieoftheweek_DetailViewModel>(_selectedmovieoftheweek_NewsListControlCollection);
            }
        }
	    /// <summary>
        /// IsInternetAvailable property.
        /// </summary>		
        public override Visibility IsInternetAvailable
        {
	      get
          {
				return Visibility.Collapsed; 
           }
		}

        /// <summary>
        /// Delegate method for the Refreshmovieoftheweek_NewsListControlCollectionCommand command.
        /// </summary>
        public async void Refreshmovieoftheweek_NewsListControlCollectionCommandDelegate() 
        {
			try
			{
				LoadingMovieoftheweek_NewsListControlCollection = true;
				var items = await  _movieoftheweek_movieDataSource.Refresh();
				Movieoftheweek_NewsListControlCollection = items;
			}
            catch (Exception ex)
            {
				Movieoftheweek_NewsListControlCollection = null;
		
                Debug.WriteLine(ex.ToString());
                _dialogService.Show(Localization.AppResources.rssError + Environment.NewLine + Localization.AppResources.TryAgain);
            }
            finally
            {
				LoadingMovieoftheweek_NewsListControlCollection = false;
			}
        }
		
		
        private bool _loadingMovieoftheweek_NewsListControlCollection;
		
        public bool LoadingMovieoftheweek_NewsListControlCollection
        {
            get { return _loadingMovieoftheweek_NewsListControlCollection; }
            set { SetProperty(ref _loadingMovieoftheweek_NewsListControlCollection, value); }
        }

        private ICommand _refreshmovieoftheweek_NewsListControlCollectionCommand;

        /// <summary>
        /// Gets the Refreshmovieoftheweek_NewsListControlCollectionCommand command.
        /// </summary>
        public ICommand Refreshmovieoftheweek_NewsListControlCollectionCommand
        {
            get { return _refreshmovieoftheweek_NewsListControlCollectionCommand = _refreshmovieoftheweek_NewsListControlCollectionCommand ?? new ViewModelsBase.DelegateCommand(Refreshmovieoftheweek_NewsListControlCollectionCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the Getmovieoftheweek_NewsListControlCollectionCommand command.
        /// </summary>
        public  void Getmovieoftheweek_NewsListControlCollectionCommandDelegate(int pageNumber= 0) 
        {
				Getmovieoftheweek_NewsListControlCollectionData(pageNumber);
        }
		

        private ICommand _getmovieoftheweek_NewsListControlCollectionCommand;

        /// <summary>
        /// Gets the Getmovieoftheweek_NewsListControlCollectionCommand command.
        /// </summary>
        public ICommand Getmovieoftheweek_NewsListControlCollectionCommand
        {
            get { return _getmovieoftheweek_NewsListControlCollectionCommand = _getmovieoftheweek_NewsListControlCollectionCommand ?? new ViewModelsBase.DelegateCommand<int>(Getmovieoftheweek_NewsListControlCollectionCommandDelegate); }
        }

        private async void Getmovieoftheweek_NewsListControlCollectionData(int pageNumber = 0)
        {
	
			try
			{
				LoadingMovieoftheweek_NewsListControlCollection = true;
			
				var items = await _movieoftheweek_movieDataSource.GetData();
                Movieoftheweek_NewsListControlCollection = items;
			}
            catch (Exception ex)
            {
				Movieoftheweek_NewsListControlCollection = null;
		
                Debug.WriteLine(ex.ToString());
                _dialogService.Show(Localization.AppResources.rssError + Environment.NewLine + Localization.AppResources.TryAgain);
            }
            finally
            {
				LoadingMovieoftheweek_NewsListControlCollection = false;
			}
		}
    }
}
