// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	ViewModel.tt
// Version:		2.0
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls = WPAppStudio.Controls;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;
using IServices = WPAppStudio.Services.Interfaces;
using IViewModels = WPAppStudio.ViewModel.Interfaces;
using Localization = WPAppStudio.Localization;
using Repositories = WPAppStudio.Repositories;
using Services = WPAppStudio.Services;
using ViewModelsBase = WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of newondvd_Detail ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class newondvd_DetailViewModel : ViewModelsBase.VMBase, IViewModels.Inewondvd_DetailViewModel, ViewModelsBase.INavigable
    {       

		private readonly Repositories.newondvd_dvdDataSource _newondvd_dvdDataSource;
		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly IServices.ISpeechService _speechService;
		private readonly IServices.IShareService _shareService;
		private readonly IServices.ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="newondvd_DetailViewModel" /> class.
        /// </summary>
        /// <param name="newondvd_dvdDataSource">The Newondvd_dvd Data Source.</param>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public newondvd_DetailViewModel(Repositories.newondvd_dvdDataSource newondvd_dvdDataSource, IServices.IDialogService dialogService, IServices.INavigationService navigationService, IServices.ISpeechService speechService, IServices.IShareService shareService, IServices.ILiveTileService liveTileService)
        {
			_newondvd_dvdDataSource = newondvd_dvdDataSource;
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		
	
		private EntitiesBase.RssSearchResult _currentRssSearchResult;

        /// <summary>
        /// CurrentRssSearchResult property.
        /// </summary>		
        public EntitiesBase.RssSearchResult CurrentRssSearchResult
        {
            get
            {
				return _currentRssSearchResult;
            }
            set
            {
                SetProperty(ref _currentRssSearchResult, value);
            }
        }
	
		private bool _hasNextpanoramanewondvd_Detail0;

        /// <summary>
        /// HasNextpanoramanewondvd_Detail0 property.
        /// </summary>		
        public bool HasNextpanoramanewondvd_Detail0
        {
            get
            {
				return _hasNextpanoramanewondvd_Detail0;
            }
            set
            {
                SetProperty(ref _hasNextpanoramanewondvd_Detail0, value);
            }
        }
	
		private bool _hasPreviouspanoramanewondvd_Detail0;

        /// <summary>
        /// HasPreviouspanoramanewondvd_Detail0 property.
        /// </summary>		
        public bool HasPreviouspanoramanewondvd_Detail0
        {
            get
            {
				return _hasPreviouspanoramanewondvd_Detail0;
            }
            set
            {
                SetProperty(ref _hasPreviouspanoramanewondvd_Detail0, value);
            }
        }
	    /// <summary>
        /// IsInternetAvailable property.
        /// </summary>		
        public override Visibility IsInternetAvailable
        {
	      get
          {
				return Visibility.Collapsed; 
           }
		}

        /// <summary>
        /// Delegate method for the TextToSpeechnewondvd_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechnewondvd_DetailStaticControlCommandDelegate() 
        {
				_speechService.TextToSpeech(CurrentRssSearchResult.Title + " " + CurrentRssSearchResult.Content);
        }
		

        private ICommand _textToSpeechnewondvd_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechnewondvd_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechnewondvd_DetailStaticControlCommand
        {
            get { return _textToSpeechnewondvd_DetailStaticControlCommand = _textToSpeechnewondvd_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(TextToSpeechnewondvd_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the Sharenewondvd_DetailStaticControlCommand command.
        /// </summary>
        public  void Sharenewondvd_DetailStaticControlCommandDelegate() 
        {
				_shareService.Share(CurrentRssSearchResult.Title, CurrentRssSearchResult.Content, CurrentRssSearchResult.FeedUrl, CurrentRssSearchResult.ImageUrl);
        }
		

        private ICommand _sharenewondvd_DetailStaticControlCommand;

        /// <summary>
        /// Gets the Sharenewondvd_DetailStaticControlCommand command.
        /// </summary>
        public ICommand Sharenewondvd_DetailStaticControlCommand
        {
            get { return _sharenewondvd_DetailStaticControlCommand = _sharenewondvd_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(Sharenewondvd_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartnewondvd_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartnewondvd_DetailStaticControlCommandDelegate() 
        {
				_liveTileService.PinToStart(typeof(IViewModels.Inewondvd_DetailViewModel), CreateTileInfonewondvd_DetailStaticControl());
        }
		

        private ICommand _pinToStartnewondvd_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartnewondvd_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartnewondvd_DetailStaticControlCommand
        {
            get { return _pinToStartnewondvd_DetailStaticControlCommand = _pinToStartnewondvd_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(PinToStartnewondvd_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the GoToSourcenewondvd_DetailStaticControlCommand command.
        /// </summary>
        public  void GoToSourcenewondvd_DetailStaticControlCommandDelegate() 
        {
				_navigationService.NavigateTo(string.IsNullOrEmpty(CurrentRssSearchResult.FeedUrl) ? null : new Uri(CurrentRssSearchResult.FeedUrl));
        }
		

        private ICommand _goToSourcenewondvd_DetailStaticControlCommand;

        /// <summary>
        /// Gets the GoToSourcenewondvd_DetailStaticControlCommand command.
        /// </summary>
        public ICommand GoToSourcenewondvd_DetailStaticControlCommand
        {
            get { return _goToSourcenewondvd_DetailStaticControlCommand = _goToSourcenewondvd_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(GoToSourcenewondvd_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the Nextpanoramanewondvd_Detail0 command.
        /// </summary>
        public async void Nextpanoramanewondvd_Detail0Delegate() 
        {
				LoadingCurrentRssSearchResult = true;
			var next = await  _newondvd_dvdDataSource.Next(CurrentRssSearchResult);

			if(next != null)
				CurrentRssSearchResult = next;

			RefreshHasPrevNext();
        }
		
		
        private bool _loadingCurrentRssSearchResult;
		
        public bool LoadingCurrentRssSearchResult
        {
            get { return _loadingCurrentRssSearchResult; }
            set { SetProperty(ref _loadingCurrentRssSearchResult, value); }
        }

        private ICommand _nextpanoramanewondvd_Detail0;

        /// <summary>
        /// Gets the Nextpanoramanewondvd_Detail0 command.
        /// </summary>
        public ICommand Nextpanoramanewondvd_Detail0
        {
            get { return _nextpanoramanewondvd_Detail0 = _nextpanoramanewondvd_Detail0 ?? new ViewModelsBase.DelegateCommand(Nextpanoramanewondvd_Detail0Delegate); }
        }

        /// <summary>
        /// Delegate method for the Previouspanoramanewondvd_Detail0 command.
        /// </summary>
        public async void Previouspanoramanewondvd_Detail0Delegate() 
        {
				LoadingCurrentRssSearchResult = true;
			var prev = await  _newondvd_dvdDataSource.Previous(CurrentRssSearchResult);

			if(prev != null)
				CurrentRssSearchResult = prev;

			RefreshHasPrevNext();
        }
		

        private ICommand _previouspanoramanewondvd_Detail0;

        /// <summary>
        /// Gets the Previouspanoramanewondvd_Detail0 command.
        /// </summary>
        public ICommand Previouspanoramanewondvd_Detail0
        {
            get { return _previouspanoramanewondvd_Detail0 = _previouspanoramanewondvd_Detail0 ?? new ViewModelsBase.DelegateCommand(Previouspanoramanewondvd_Detail0Delegate); }
        }

        private async void RefreshHasPrevNext()
        {
            HasPreviouspanoramanewondvd_Detail0 = await _newondvd_dvdDataSource.HasPrevious(CurrentRssSearchResult);
			HasNextpanoramanewondvd_Detail0 = await _newondvd_dvdDataSource.HasNext(CurrentRssSearchResult);
			LoadingCurrentRssSearchResult = false;
		}
		public object NavigationContext
        {
            set
            {              
                if (!(value is EntitiesBase.RssSearchResult)) { return; }
                
                CurrentRssSearchResult = value as EntitiesBase.RssSearchResult;
                RefreshHasPrevNext();
            }
        }
        /// <summary>
        /// Initializes a <see cref="Services.TileInfo" /> object for the newondvd_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="Services.TileInfo" /> object.</returns>
        public Services.TileInfo CreateTileInfonewondvd_DetailStaticControl()
        {
            var tileInfo = new Services.TileInfo
            {
                CurrentId = CurrentRssSearchResult.Title,
                Title = CurrentRssSearchResult.Title,
                BackTitle = CurrentRssSearchResult.Title,
                BackContent = CurrentRssSearchResult.Content,
                Count = 0,
                BackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                BackBackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                LogoPath = "Logo-ee1683e8-d47b-47fb-83b9-cfccc204fafa.png"
            };
            return tileInfo;
        }
    }
}
