// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IViewModel.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// intheaters_News ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface Iintheaters_NewsViewModel
    {		
        /// <summary>
        /// Gets/Sets the Intheaters_NewsListControlCollection property.
        /// </summary>
		ObservableCollection<EntitiesBase.RssSearchResult> Intheaters_NewsListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the Selectedintheaters_NewsListControlCollection property.
        /// </summary>
		EntitiesBase.RssSearchResult Selectedintheaters_NewsListControlCollection { get; set; }
	    /// <summary>
        /// IsInternetAvailable property.
        /// </summary>		
        Visibility IsInternetAvailable { get; }
        
        /// <summary>
        /// Gets the Refreshintheaters_NewsListControlCollectionCommand command.
        /// </summary>
		ICommand Refreshintheaters_NewsListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the Getintheaters_NewsListControlCollectionCommand command.
        /// </summary>
		ICommand Getintheaters_NewsListControlCollectionCommand { get; }

	}
}
