// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IViewModel.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// intheaters_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface Iintheaters_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRssSearchResult property.
        /// </summary>
		EntitiesBase.RssSearchResult CurrentRssSearchResult { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramaintheaters_Detail0 property.
        /// </summary>
		bool HasNextpanoramaintheaters_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramaintheaters_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramaintheaters_Detail0 { get; set; }
	    /// <summary>
        /// IsInternetAvailable property.
        /// </summary>		
        Visibility IsInternetAvailable { get; }
        
        /// <summary>
        /// Gets the TextToSpeechintheaters_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechintheaters_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the Shareintheaters_DetailStaticControlCommand command.
        /// </summary>
		ICommand Shareintheaters_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartintheaters_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartintheaters_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourceintheaters_DetailStaticControlCommand command.
        /// </summary>
		ICommand GoToSourceintheaters_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the Nextpanoramaintheaters_Detail0 command.
        /// </summary>
		ICommand Nextpanoramaintheaters_Detail0 { get; }

        
        /// <summary>
        /// Gets the Previouspanoramaintheaters_Detail0 command.
        /// </summary>
		ICommand Previouspanoramaintheaters_Detail0 { get; }

	}
}
