// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IViewModel.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// movieoftheweek_News ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface Imovieoftheweek_NewsViewModel
    {		
        /// <summary>
        /// Gets/Sets the Movieoftheweek_NewsListControlCollection property.
        /// </summary>
		ObservableCollection<EntitiesBase.RssSearchResult> Movieoftheweek_NewsListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the Selectedmovieoftheweek_NewsListControlCollection property.
        /// </summary>
		EntitiesBase.RssSearchResult Selectedmovieoftheweek_NewsListControlCollection { get; set; }
	    /// <summary>
        /// IsInternetAvailable property.
        /// </summary>		
        Visibility IsInternetAvailable { get; }
        
        /// <summary>
        /// Gets the Refreshmovieoftheweek_NewsListControlCollectionCommand command.
        /// </summary>
		ICommand Refreshmovieoftheweek_NewsListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the Getmovieoftheweek_NewsListControlCollectionCommand command.
        /// </summary>
		ICommand Getmovieoftheweek_NewsListControlCollectionCommand { get; }

	}
}
