// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IViewModel.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// movieoftheweek_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface Imovieoftheweek_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRssSearchResult property.
        /// </summary>
		EntitiesBase.RssSearchResult CurrentRssSearchResult { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramamovieoftheweek_Detail0 property.
        /// </summary>
		bool HasNextpanoramamovieoftheweek_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramamovieoftheweek_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramamovieoftheweek_Detail0 { get; set; }
	    /// <summary>
        /// IsInternetAvailable property.
        /// </summary>		
        Visibility IsInternetAvailable { get; }
        
        /// <summary>
        /// Gets the TextToSpeechmovieoftheweek_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechmovieoftheweek_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the Sharemovieoftheweek_DetailStaticControlCommand command.
        /// </summary>
		ICommand Sharemovieoftheweek_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartmovieoftheweek_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartmovieoftheweek_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourcemovieoftheweek_DetailStaticControlCommand command.
        /// </summary>
		ICommand GoToSourcemovieoftheweek_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the Nextpanoramamovieoftheweek_Detail0 command.
        /// </summary>
		ICommand Nextpanoramamovieoftheweek_Detail0 { get; }

        
        /// <summary>
        /// Gets the Previouspanoramamovieoftheweek_Detail0 command.
        /// </summary>
		ICommand Previouspanoramamovieoftheweek_Detail0 { get; }

	}
}
