// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IViewModel.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// newondvd_News ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface Inewondvd_NewsViewModel
    {		
        /// <summary>
        /// Gets/Sets the Newondvd_NewsListControlCollection property.
        /// </summary>
		ObservableCollection<EntitiesBase.RssSearchResult> Newondvd_NewsListControlCollection { get; set; }
        /// <summary>
        /// Gets/Sets the Selectednewondvd_NewsListControlCollection property.
        /// </summary>
		EntitiesBase.RssSearchResult Selectednewondvd_NewsListControlCollection { get; set; }
	    /// <summary>
        /// IsInternetAvailable property.
        /// </summary>		
        Visibility IsInternetAvailable { get; }
        
        /// <summary>
        /// Gets the Refreshnewondvd_NewsListControlCollectionCommand command.
        /// </summary>
		ICommand Refreshnewondvd_NewsListControlCollectionCommand { get; }

        
        /// <summary>
        /// Gets the Getnewondvd_NewsListControlCollectionCommand command.
        /// </summary>
		ICommand Getnewondvd_NewsListControlCollectionCommand { get; }

	}
}
